config/routes.rb
Rails.application.routes.draw do

  devise_for :administrators
  get 'administrators/dashboard', as: 'administrator_root'

  devise_for :customers
  get 'customers/dashboard', as: 'customer_root'

  root 'site/pages#home'


  namespace :administrators do
    resources :product_categories, only: [:index, :create] do
      get 'add_children', on: :member
      get 'add_product', on: :member
    end
    resources :products, only: [:create]
    resources :orders, only: [:index, :show]  
  end  

  scope module: 'site' do
    resources :products, only: [:show] do
      post 'add_to_cart', on: :member
    end  
    resources :carts, only: [:show, :destroy] do
      post 'remove_item', on: :member
    end  

    resources :orders, only: [:create]
  end


end

app/models/administrator.rb
class Administrator < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord



end

app/models/cart_product.rb
class CartProduct < ApplicationRecord

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord

 

end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
end

app/controllers/administrators/orders_controller.rb
class Administrators::OrdersController < AdministratorsController

  def index
    @orders = Orm::Order.get_all_items
  end

  def show
    @order = Orm::Order.get_item(params[:id])
    @product_items = Orm::Order.get_order_product_items(params[:id])
  end

end  

app/controllers/administrators/product_categories_controller.rb
class Administrators::ProductCategoriesController < AdministratorsController

  def index
    @all_categories = Orm::ProductCategory.get_all_items
  end

  def add_children
    @new_category = ProductCategory.new
    @parent_id = params[:id]
  end

  def create
    cat_params = params.require(:product_category)
    Orm::ProductCategory.create(cat_params[:parent_id], cat_params[:name])
    redirect_to administrators_product_categories_path
  end

  def add_product
    @new_product = Product.new
    @parent_id = params[:id]
  end

end  

app/controllers/administrators/products_controller.rb
class Administrators::ProductsController < AdministratorsController

  def create
    prod_params = params.require(:product)
    result = Orm::ProductCategory.add_product(prod_params[:parent_id], prod_params[:name], prod_params[:price])
     Rails.logger.error "\e[31m result: #{result} \n \n \e[0m"
    if result
      redirect_to product_path(result)
    else
      redirect_to administrators_product_categories_path
    end
  end

end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  
  before_action :authenticate_administrator!
  protect_from_forgery with: :exception

  layout "administrator"

  def after_sign_in_path_for(resource)
    admnistrator_root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    request.referrer
  end

  def dashboard
    render "/administrators/dashboard"
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  before_action :authenticate_customer!
  protect_from_forgery with: :exception

  layout "customer"

  def after_sign_in_path_for(resource)
    customer_root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    request.referrer
  end

  def dashboard
    render "/customers/dashboard"
  end


end

app/controllers/site/carts_controller.rb
class Site::CartsController < SiteController

  def show
    @items = Orm::Cart.get_all_items(@cart[:id])
    @new_order = Order.new
  end

  def remove_item
    result = Orm::Cart.remove_item(@cart, params[:id])
    redirect_to cart_path(@cart)
  end

end  

app/controllers/site/orders_controller.rb
class Site::OrdersController < SiteController

  def create
    result = Orm::Cart.create_order(@cart, params[:order][:customer_notice])
    if result
      redirect_to root_path, notice: 'Заказ оформлен, спасибо'
    else
      redirect_back(fallback_location: cart_path(@cart))
    end
  end



end

app/controllers/site/pages_controller.rb
class Site::PagesController < SiteController

  def home
    @products = Orm::Product.get_all_items
    render '/site/home'
  end


end

app/controllers/site/products_controller.rb
class Site::ProductsController < SiteController

  def show
    @product = Orm::Product.find_by_id(params[:id])
    unless @product 
      render file: "#{Rails.root}/public/404", layout: false, status: :not_found
    end  
  end

  # добавление в корзину зарегистрированным пользователем
  def add_to_cart
    Orm::Cart.add_product(@cart[:id], params[:id])
    redirect_to cart_path(@cart)
  end
    
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  before_action :all_pages_data

  def all_pages_data
    @cart = Orm::Cart.get_current_customer_cart(current_customer.id) if current_customer
    @cart = nil unless current_customer
  end


end

app/views/administrators/dashboard.html.erb
<h2>This is administrator dashboard page</h2>
<%= link_to 'Выйти', destroy_administrator_session_path, method: :delete %>

app/views/administrators/orders/index.html.erb
<h2>Заказы</h2>
  
<table>
  <tr>
    <th>id</th> <th>customer_id</th> <th>customer_notice</th> <th></th>
  </tr>
  <% @orders.each do |order| %>
  <tr>
    <td><%= order['id'] %></td>
    <td><%= order['customer_id'] %></td>
    <td><%= order['customer_notice'] %></td>     
    <td><%= link_to "Посмотреть", administrators_order_path(order['id']) %></td>
  </tr>
  <% end %>
</table>

app/views/administrators/orders/show.html.erb
<h2>Заказ №<%= @order[:id] %></h2>

<table>
  <tr>
    <th>product_id</th><th>product_name</th><th>product_price</th> <th>product_qty</th><th>total_price</th><th></th>
  </tr>
  <% @product_items.each do |item| %>
  <tr>
    <td><%= item['product_id'] %></td>
    <td><%= item['name'] %></td>  
    <td><%= item['product_price'] %></td>
    <td><%= item['product_qty'] %></td>  
    <td><%= item['product_total_price'] %></td>      
  </tr>
  <% end %>
</table>

app/views/administrators/product_categories/add_children.html.erb
<h2>Добавление дочерней категории к родтельской</h2>
<%= form_for([:administrators, @new_category], multipart: true ) do |f| %>
  <%= f.text_area :name, placeholder: 'Имя' %><br/>
  <%= f.hidden_field(:parent_id, value: @parent_id) %>
  <%= f.submit 'Отправить' %>
<% end %>

app/views/administrators/product_categories/add_product.html.erb
<h2>Добавление товара к категории</h2>
<%= form_for([:administrators, @new_product], multipart: true ) do |f| %>
  <%= f.text_field :name, placeholder: 'Имя' %><br/>
  <%= f.text_field :price, placeholder: 'Цена' %><br/>
  <%= f.hidden_field(:parent_id, value: @parent_id) %>
  <%= f.submit 'Отправить' %>
<% end %>

app/views/administrators/product_categories/index.html.erb
<table>
  <tr>
    <th>id</th><th>Название</th><th>id родителя</th> <th>Глубина</th><th>Иерархия</th><th></th>
  </tr>
  <% @all_categories.each do |category| %>
  <tr>
    <td><%= category['id'] %></td>
    <td><%= category['name'] %></td>  
    <td><%= category['product_category_id'] %></td>
    <td><%= category['depth'] %></td>  
    <td><%= category['sort_string'] %></td> 
    <td>
      <%= link_to 'добавить дочернюю', add_children_administrators_product_category_path(category['id']) %> | 
      <%= link_to 'добавить товар', add_product_administrators_product_category_path(category['id']) %>
    </td>     
  </tr>
  <% end %>
</table>

app/views/customers/dashboard.html.erb
<h2>This is customer dashboard page</h2>
<%= link_to 'Выйти', destroy_customer_session_path, method: :delete %>

app/views/layouts/administrator.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Панель управления администратора</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'administrator', media: 'all' %>
  </head>

  <body>
    <hr/>
      <p><%= link_to 'Категории товаров', administrators_product_categories_path() %> | 
         <%= link_to 'Заказы', administrators_orders_path() %>
      </p>
    <hr>
    <%= yield %>
    <%= javascript_include_tag 'administrator' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/customer.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Аккаунт покупателя</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'customer', media: 'all' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'customer' %>
  </body>
</html>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Общедоступная часть</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'site', media: 'all' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <hr/>
      <p>cart: <%= @cart %> <%= link_to 'Перейти', cart_path(@cart[:id]) %>, cart_class: <%= @cart.class %>,  customer: <%= current_customer %>, notice: <%= flash[:notice] %> </p>
    <hr/>
    <%= yield %>
    <%= javascript_include_tag 'site' %>
  </body>
</html>

app/views/site/carts/show.html.erb
<h2>Корзина</h2>

<table>
  <tr>
    <th>id</th> <th>product_id</th> <th>cart_id</th>  <th>product_price</th> <th>product_qty</th><th>total_price</th><th></th>
  </tr>
  <% @items.each do |item| %>
  <tr>
    <td><%= item['id'] %></td>
    <td><%= item['product_id'] %></td>
    <td><%= item['cart_id'] %></td>  
    <td><%= item['product_price'] %></td>
    <td><%= item['product_qty'] %></td>  
    <td><%= item['product_total_price'] %></td>      
    <td><%= button_to 'удалить', remove_item_cart_path(item['id']) %></td>
  </tr>
  <% end %>
</table>

<h3>Оформить заказ</h3>
<%= form_for @new_order do |f| %>
  <%= f.text_area :customer_notice, placeholder: 'Примечание к заказу' %><br/>
  <%= f.submit 'Отправить' %>
<% end %>

app/views/site/home.html.erb
<p>Главная страница сайта</p>

<hr/>
для администратора:
<% if administrator_signed_in? %>
    <span>Авторизован, <%= current_administrator.email %></span>
    <%= link_to 'Выйти', destroy_administrator_session_path, :method => :delete %>
<% else %>
    <%= link_to 'Войти', new_administrator_session_path %> или <%= link_to 'Зарегистрироваться', new_administrator_registration_path %>
<% end %>
<hr/>
для покупателя:
<% if customer_signed_in? %>
    <span>Авторизован, <%= current_customer.email %></span>
    <%= link_to 'Выйти', destroy_customer_session_path, :method => :delete %>
<% else %>
    <%= link_to 'Войти', new_customer_session_path %> или <%= link_to 'Зарегистрироваться', new_customer_registration_path %>
<% end %>
<hr/>


<table>
  <tr>
    <th>id</th> <th>Название</th> <th>Цена</th><th></th>
  </tr>
  <% @products.each do |product| %>
  <tr>
    <td><%= product['id'] %></td><td><%= product['name'] %></td><td><%= product['price'] %></td> <td><%= link_to 'Перейти', product_path(product['id']) %></td>
  </tr>
  <% end %>
</table>

app/views/site/products/show.html.erb
<h2>Страница товара</h2>

<%= @product %>
<hr/>


<% if current_customer %>
  <%= button_to 'Добавить в корзину', add_to_cart_product_path(@product[:id]), {method: :post} %>
<% else %>  
  <p>Чтобы купить товар нужно <%= link_to 'войти', new_customer_session_path %> или <%= link_to 'зарегистрироваться', new_customer_registration_path %>.</p>
<% end %>